"""Centralised configuration loaded from environment / .env.

The Electron shell and the Python core share the same loopback connection
settings. Legacy ``JARVIS_*`` names remain supported for compatibility.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Mapping

# Electron injects these values to create a private loopback boundary. Keep a
# snapshot before loading user configuration so a stale or malicious .env
# cannot redirect the desktop process or replace its per-launch token.
_DESKTOP_LAUNCH = os.getenv("AETHER_DESKTOP") == "1"
_DESKTOP_NETWORK_KEYS = ("AETHER_API_TOKEN", "JARVIS_HOST", "JARVIS_PORT")
_SECURE_SECRET_MAP = {
    "AETHER_SECURE_GEMINI_API_KEY": "GEMINI_API_KEY",
    "AETHER_SECURE_LLM_API_KEY": "LLM_API_KEY",
    "AETHER_SECURE_ELEVENLABS_API_KEY": "ELEVENLABS_API_KEY",
    "AETHER_SECURE_WEATHER_API_KEY": "WEATHER_API_KEY",
    "AETHER_SECURE_GOOGLE_CLIENT_CREDENTIALS_JSON": "GOOGLE_CLIENT_CREDENTIALS_JSON",
    "AETHER_SECURE_GMAIL_OAUTH_TOKEN_JSON": "GMAIL_OAUTH_TOKEN_JSON",
    "AETHER_SECURE_CALENDAR_OAUTH_TOKEN_JSON": "CALENDAR_OAUTH_TOKEN_JSON",
}
_DESKTOP_TRUSTED_KEYS = (
    *_DESKTOP_NETWORK_KEYS,
    "AETHER_VAULT_ENFORCED",
    *_SECURE_SECRET_MAP,
)
_DESKTOP_NETWORK_ENV = (
    {key: os.environ.get(key) for key in _DESKTOP_TRUSTED_KEYS}
    if _DESKTOP_LAUNCH
    else {}
)

try:
    from dotenv import load_dotenv
except ImportError:  # lets lightweight tooling inspect the project before setup
    def load_dotenv(*_args, **_kwargs) -> bool:
        return False

# Look for .env in the project root and python/ folder, in that order.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(_PROJECT_ROOT / ".env")
load_dotenv(_PROJECT_ROOT / "python" / ".env")
if os.getenv("JARVIS_ENV_FILE"):
    load_dotenv(Path(os.environ["JARVIS_ENV_FILE"]), override=True)

if _DESKTOP_LAUNCH:
    for _key, _value in _DESKTOP_NETWORK_ENV.items():
        if _value is None:
            os.environ.pop(_key, None)
        else:
            os.environ[_key] = _value
    # Electron decrypts these values with safeStorage for this process. They
    # deliberately win over .env/JARVIS_ENV_FILE so a local file cannot replace
    # the credential selected in the desktop settings screen.
    if os.getenv("AETHER_VAULT_ENFORCED") == "1":
        # A denied/revoked grant is represented by the absence of its secure
        # launch variable.  Remove legacy values loaded from .env before
        # projecting effective vault grants into the standard names used by
        # provider clients.
        for _standard_key in {
            *_SECURE_SECRET_MAP.values(),
            "OPENWEATHER_API_KEY",
        }:
            os.environ.pop(_standard_key, None)
    for _secure_key, _standard_key in _SECURE_SECRET_MAP.items():
        _secure_value = os.environ.get(_secure_key)
        if _secure_value:
            os.environ[_standard_key] = _secure_value


_STANDARD_SECRET_KEYS = (
    "AETHER_API_TOKEN",
    "GEMINI_API_KEY",
    "LLM_API_KEY",
    "ELEVENLABS_API_KEY",
    "WEATHER_API_KEY",
    "OPENWEATHER_API_KEY",
    "GOOGLE_CLIENT_CREDENTIALS_JSON",
    "GMAIL_OAUTH_TOKEN_JSON",
    "CALENDAR_OAUTH_TOKEN_JSON",
)
_SECURE_SECRET_KEYS = tuple(_SECURE_SECRET_MAP)
_CAPTURED_SECRETS: dict[str, str] = {
    key: value
    for key in (*_STANDARD_SECRET_KEYS, *_SECURE_SECRET_KEYS)
    if (value := os.environ.get(key))
}


def _secret(*names: str) -> str | None:
    """Return a launch credential captured before the environment is scrubbed."""
    for name in names:
        value = _CAPTURED_SECRETS.get(name)
        if value:
            return value
    return None


class Settings:
    """Process-wide configuration. Read-only after first import."""

    # --- Network -------------------------------------------------------------
    # The core exposes OS and file-system actions and must stay loopback-only
    # unless the user deliberately overrides this value.
    host: str = os.getenv("JARVIS_HOST", "127.0.0.1")
    port: int = int(os.getenv("JARVIS_PORT", "8765"))
    # Generated by Electron on every launch. When unset (for example during
    # local API development), the loopback service keeps its legacy behavior.
    api_token: str | None = _secret("AETHER_API_TOKEN")
    # In desktop mode the native keychain is authoritative. A denied or absent
    # grant must never fall back to an old token file or a value from .env.
    vault_enforced: bool = (
        _DESKTOP_LAUNCH and os.getenv("AETHER_VAULT_ENFORCED") == "1"
    )

    # --- Storage -------------------------------------------------------------
    data_dir: Path = Path(os.getenv("JARVIS_DATA_DIR", str(_PROJECT_ROOT / "jarvis_data")))
    short_term_db_path: Path = data_dir / "short_term.sqlite3"
    vector_db_path: Path = data_dir / "vector_store"
    logs_dir: Path = data_dir / "logs"

    data_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    vector_db_path.mkdir(parents=True, exist_ok=True)

    # --- LLM Provider (multi-model) ------------------------------------------
    # Provider type: "gemini" | "glm" | "openai" | "ollama"
    llm_provider: str = os.getenv("LLM_PROVIDER", "gemini")
    # Generic API key (used by GLM, OpenAI, etc.)
    llm_api_key: str | None = _secret("LLM_API_KEY")
    # Base URL for OpenAI-compatible providers (DeepSeek, Anthropic, etc.)
    llm_base_url: str | None = os.getenv("LLM_BASE_URL")
    # Model name (provider-specific)
    llm_model: str | None = os.getenv("LLM_MODEL")
    # Ollama-specific
    ollama_base_url: str = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")

    # --- Models --------------------------------------------------------------
    # Voice ID requested by spec: "dX7gRq1dIvLTgUaWpEFn"
    elevenlabs_voice_id: str = os.getenv("ELEVENLABS_VOICE_ID", "dX7gRq1dIvLTgUaWpEFn")
    elevenlabs_api_key: str | None = _secret("ELEVENLABS_API_KEY")
    # Gemini API key (kept for backward compatibility)
    gemini_api_key: str | None = _secret("GEMINI_API_KEY", "LLM_API_KEY")
    weather_api_key: str | None = _secret(
        "WEATHER_API_KEY",
        "OPENWEATHER_API_KEY",
    )
    google_client_credentials_json: str | None = _secret(
        "GOOGLE_CLIENT_CREDENTIALS_JSON",
    )
    gmail_oauth_token_json: str | None = _secret(
        "GMAIL_OAUTH_TOKEN_JSON",
    )
    calendar_oauth_token_json: str | None = _secret(
        "CALENDAR_OAUTH_TOKEN_JSON",
    )

    # Optional local Whisper model size (tiny|base|small|medium|large).
    whisper_model: str = os.getenv("JARVIS_WHISPER_MODEL", "base")

    # --- Computer vision -----------------------------------------------------
    cv_enabled: bool = os.getenv("JARVIS_CV_ENABLED", "1") == "1"
    # Cache directory for face encodings (1 file per known person).
    faces_dir: Path = data_dir / "faces"
    faces_dir.mkdir(parents=True, exist_ok=True)

    # --- Agent config --------------------------------------------------------
    agent_orchestrator_model: str = os.getenv("JARVIS_AGENT_MODEL", "gemini-2.0-flash")


settings = Settings()

# Credentials are process input, not process-wide configuration.  Keeping them
# in ``os.environ`` would silently pass them to every Git hook, project test,
# plugin helper or desktop program spawned later.  Provider clients retain the
# values above in memory; child processes receive a deliberately minimal
# environment through ``minimal_subprocess_env``.
for _secret_key in (*_STANDARD_SECRET_KEYS, *_SECURE_SECRET_KEYS):
    os.environ.pop(_secret_key, None)


_SAFE_ENV_EXACT = frozenset({
    # Executable and runtime discovery.
    "PATH",
    "PATHEXT",
    "SYSTEMROOT",
    "WINDIR",
    "COMSPEC",
    "VIRTUAL_ENV",
    # User and temporary directories used by normal command-line tools.
    "HOME",
    "HOMEDRIVE",
    "HOMEPATH",
    "USER",
    "USERNAME",
    "USERPROFILE",
    "LOGNAME",
    "APPDATA",
    "LOCALAPPDATA",
    "PROGRAMDATA",
    "PROGRAMFILES",
    "PROGRAMFILES(X86)",
    "PROGRAMW6432",
    "TEMP",
    "TMP",
    "TMPDIR",
    # Locale/terminal/display integration.
    "LANG",
    "LANGUAGE",
    "TERM",
    "COLORTERM",
    "DISPLAY",
    "WAYLAND_DISPLAY",
    "DBUS_SESSION_BUS_ADDRESS",
    "XAUTHORITY",
    "DESKTOP_SESSION",
    "GDK_BACKEND",
    "QT_QPA_PLATFORM",
    "PULSE_SERVER",
    "SSH_AUTH_SOCK",
    # OS architecture hints used by installers and launchers.
    "OS",
    "PROCESSOR_ARCHITECTURE",
    "PROCESSOR_ARCHITEW6432",
    "NUMBER_OF_PROCESSORS",
    "SESSIONNAME",
    "__CF_USER_TEXT_ENCODING",
})
_SAFE_ENV_PREFIXES = ("LC_", "XDG_")
_SENSITIVE_ENV_MARKERS = (
    "API_KEY",
    "APIKEY",
    "AUTHORIZATION",
    "BEARER",
    "COOKIE",
    "CREDENTIAL",
    "PASSWORD",
    "PRIVATE_KEY",
    "SECRET",
    "SESSION_TOKEN",
    "ACCESS_TOKEN",
    "REFRESH_TOKEN",
)


def _sensitive_environment_name(name: str) -> bool:
    normalized = str(name or "").strip().upper()
    return (
        normalized in _STANDARD_SECRET_KEYS
        or normalized in _SECURE_SECRET_KEYS
        or normalized.startswith("AETHER_SECURE_")
        or any(marker in normalized for marker in _SENSITIVE_ENV_MARKERS)
        or normalized.endswith("_TOKEN")
    )


def minimal_subprocess_env(
    extra: Mapping[str, object] | None = None,
) -> dict[str, str]:
    """Build a bounded environment for commands launched by Aether.

    Only OS/runtime discovery variables are inherited.  Callers may add
    non-sensitive values explicitly; credential-shaped keys are rejected even
    when supplied through ``extra``.
    """
    output = {
        key: value
        for key, value in os.environ.items()
        if (
            key.upper() in _SAFE_ENV_EXACT
            or key.upper().startswith(_SAFE_ENV_PREFIXES)
        )
        and not _sensitive_environment_name(key)
    }
    for raw_key, raw_value in dict(extra or {}).items():
        key = str(raw_key)
        if not key or _sensitive_environment_name(key) or raw_value is None:
            continue
        output[key] = str(raw_value)
    return output
